# Generated by Django 5.1.4 on 2024-12-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
