# Generated by Django 5.1.4 on 2025-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
